blank_issues_enabled: false
contact_links:
  - name: "Discussões"
    url: "https://github.com/5-5-5-5-5-5-5/prometheus/discussions"
    about: "Use GitHub Discussions para perguntas gerais e sugestões."
